name: "CI"
on:
  push:
    branches:
      - master
  pull_request:

env:
  TEST_IMAGE_NAME: hadolint-action:${{github.sha}}

jobs:
  lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run hadolint
        run: hadolint Dockerfile
